### ISSUE TITLE
Can't access updated state in onEnter

### ISSUE THREAD

**Issue by guacamoli** [bitmap/react-hook-inview#3]
Hi,

I'm trying to access state that has changed when my component comes into view but it seems that the state is locked to when the hook is initialized.

 ```
const [someValue, setSomeValue] = useState(1111);

// Only call once.
  useEffect(() => {
    setSomeValue(2222)
  }, []);

  useInView({
    target: element,
    threshold: 0.25,
    onEnter: () => { console.log(someValue) },
    unobserveOnEnter: true
  }, [someValue]);
```

When the item comes into view, onEnter is called but the output is "1111" rather than "2222" even though the state has been updated. What is the right way to be able to access the state in the onEnter callback?

**Comment by bitmap** [comment]
`useInView` is using its own `useEffect` under the hood, and you're right, state is locked in because it only gets updated on first render.

So this is definitely a case I hadn't considered, the `onEnter` callback is usually used to _set_ state in your component based on data from the entry. But I can definitely see the need to access updated state.

Interesting that you added `[someValue]` as the second argument in the hook. Currently that's not doing anything. However, I can update it to pass that argument to the internal hook which would trigger an update.

Gimme a few, I'll publish an update after I test this out.

**Comment by guacamoli** [comment]
> Interesting that you added [someValue] 

Hey @bitmap, yep I added it as more of an example of a potential approach. Appreciate the quick response!

**Comment by bitmap** [comment]
No prob @guacamoli. You can now pass state as a second argument to the hook in [version `3.0.0`](https://www.npmjs.com/package/react-hook-inview/v/3.0.0) to get updated state in the callback. And thanks for using my package!
